apiVersion: v1
kind: Service
metadata:
  name: marketai-api-service
  labels:
    app: marketai-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: marketai-api
