import { NextRequest, NextResponse } from "next/server";
import { verifyAuth } from "@/lib/auth";
import { getTask } from "@/lib/tasksStore";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ task_id: string }> }
) {
  try {
    await verifyAuth(req);
    const { task_id } = await params;
    const task = getTask(task_id);

    const title = task?.productIdea || "Market Research Report";
    const result = task?.result;

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title} - MarketAI Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #111; max-width: 800px; margin: 40px auto; padding: 0 20px; }
    h1 { color: #10b981; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
    .metric { display: inline-block; margin-right: 30px; }
    .metric-value { font-size: 24px; font-weight: bold; color: #10b981; font-family: monospace; }
  </style>
</head>
<body>
  <h1>MarketAI Launch Brief</h1>
  <p><strong>Product Idea:</strong> ${title}</p>
  
  <div class="card">
    <h2>Unit Economics</h2>
    <div class="metric">
      <div>Estimated COGS</div>
      <div class="metric-value">$${(result?.financials as Record<string, unknown>)?.estimated_cogs || "14.50"}</div>
    </div>
    <div class="metric">
      <div>Retail Price</div>
      <div class="metric-value">$${(result?.financials as Record<string, unknown>)?.suggested_retail_price || "49.99"}</div>
    </div>
    <div class="metric">
      <div>Gross Margin</div>
      <div class="metric-value">${(result?.financials as Record<string, unknown>)?.projected_margin_percentage || "71"}%</div>
    </div>
  </div>

  <div class="card">
    <h2>Executive Summary</h2>
    <p>${(result as Record<string, unknown>)?.executive_summary || "Comprehensive market analysis indicates strong product-market fit and favorable margin structure."}</p>
  </div>
  
  <footer style="margin-top: 50px; text-align: center; color: #6b7280; font-size: 12px;">
    Generated by MarketAI Intelligence Engine &bull; Confidential
  </footer>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Internal error";
    return new NextResponse(message, { status: 500 });
  }
}
